# Generated by Django 4.1.7 on 2023-06-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movies_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='comments',
            field=models.ManyToManyField(to='movies.comment'),
        ),
    ]
